INSERT INTO Building_YieldChangesPerPop(BuildingType,YieldType,Yield)
VALUES ('BUILDING_GuoZijian','YIELD_SCIENCE',50);
INSERT  INTO Building_YieldChanges(BuildingType,YieldType,Yield)
VALUES  ('BUILDING_QianQingGong_PALACE','YIELD_CULTURE',5),
        ('BUILDING_QianQingGong_PALACE','YIELD_SCIENCE',3),
        ('BUILDING_QianQingGong_PALACE','YIELD_PRODUCTION',3),
        ('BUILDING_QianQingGong_PALACE','YIELD_GOLD',5),
        ('BUILDING_QianQingGong_PALACE','YIELD_FOOD',5),
        ('BUILDING_QianQingGong_PALACE','YIELD_FAITH',5);
INSERT  INTO Building_ResourceQuantity(BuildingType,ResourceType,Quantity)
VALUES  ('BUILDING_QianQingGong_PALACE','RESOURCE_MANPOWER',20),
        ('BUILDING_QianQingGong_PALACE','RESOURCE_CONSUMER',20);
INSERT INTO Building_Flavors(BuildingType,FlavorType,Flavor) 
VALUES 
       ('BUILDING_Ming_PALACE', 'FLAVOR_OFFENSE',999),
       ('BUILDING_Ming_PALACE', 'FLAVOR_DEFENSE',999),
       ('BUILDING_Ming_PALACE', 'FLAVOR_WONDER',999),
       ('BUILDING_Ming_PALACE', 'FLAVOR_MILITARY_TRAINING',999);
INSERT INTO UnitPromotions_UnitCombats(PromotionType, UnitCombatType)
VALUES
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_CARRIER'),
	('PROMOTION_Ming_PALACE', 'UNITCOMBAT_NAVALMELEE'),
	('PROMOTION_Ming_PALACE', 'UNITCOMBAT_NAVALRANGED'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_SUBMARINE'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_BOMBER'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_FIGHTER'),
	('PROMOTION_Ming_PALACE', 'UNITCOMBAT_MELEE'),
	('PROMOTION_Ming_PALACE', 'UNITCOMBAT_GUN'),
	('PROMOTION_Ming_PALACE', 'UNITCOMBAT_MOUNTED'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_ARCHER'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_HELICOPTER'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_SIEGE'),
        ('PROMOTION_Ming_PALACE', 'UNITCOMBAT_RECON'),
	('PROMOTION_Ming_PALACE', 'UNITCOMBAT_ARMOR'),
        ('PROMOTION_Ming_ShenJiYing', 'UNITCOMBAT_MELEE'),
        ('PROMOTION_Ming_ZhengHeTreasureShip', 'UNITCOMBAT_NAVALRANGED'),
	('PROMOTION_Ming_FoLangJi', 'UNITCOMBAT_SIEGE');
UPDATE UnitClasses 
SET MaxPlayerInstances = 9999 
WHERE Type = 'UNITCLASS_ZHENGHE_FLEET';
UPDATE Project_Flavors 
SET Flavor = 999
WHERE ProjectType = 'PROJECT_ZHENGHE_FLEET';
INSERT OR IGNORE INTO UnitPromotions_UnitCombats(PromotionType, UnitCombatType) 
SELECT 'PROMOTION_Ming_Dynasty_HDZhao', Type  FROM UnitCombatInfos;
INSERT  or  IGNORE  INTO Building_SpecialistYieldChanges(BuildingType,SpecialistType ,YieldType ,Yield)
SELECT  'BUILDING_GuoZijian','SPECIALIST_ARTIST','YIELD_HEALTH' ,3   
WHERE   EXISTS (SELECT * FROM ROG_GlobalUserSettings WHERE Type = 'WORLD_POWER_PATCH' AND Value = 1);