INSERT INTO IconTextureAtlases	(Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn) 
VALUES ('Ming_Dynasty_ATLAS', 256,'ICON_Ming_Dynasty256.dds', 8, 8),
       ('Ming_Dynasty_ATLAS', 128,'ICON_Ming_Dynasty128.dds', 8, 8),
	   ('Ming_Dynasty_ATLAS', 80, 'ICON_Ming_Dynasty80.dds',  8, 8),
	   ('Ming_Dynasty_ATLAS', 64, 'ICON_Ming_Dynasty64.dds',  8, 8),
	   ('Ming_Dynasty_ATLAS', 48, 'ICON_Ming_Dynasty48.dds',  8, 8),
	   ('Ming_Dynasty_ATLAS', 45, 'ICON_Ming_Dynasty45.dds',  8, 8),
	   ('Ming_Dynasty_ATLAS', 32, 'ICON_Ming_Dynasty32.dds',  8, 8),
	   ('Ming_Dynasty_ATLAS', 24, 'ICON_Ming_Dynasty24.dds',  8, 8),
	   ('Ming_Dynasty_ATLAS', 22, 'ICON_Ming_Dynasty22.dds',  8, 8),
	   ('Ming_Dynasty_ALPHA_ATLAS', 256,'ALPHA_ICON_Ming_Dynasty256.dds', 1, 1),
       ('Ming_Dynasty_ALPHA_ATLAS', 128,'ALPHA_ICON_Ming_Dynasty128.dds', 1, 1),
	   ('Ming_Dynasty_ALPHA_ATLAS', 80, 'ALPHA_ICON_Ming_Dynasty80.dds',  1, 1),
	   ('Ming_Dynasty_ALPHA_ATLAS', 64, 'ALPHA_ICON_Ming_Dynasty64.dds',  1, 1),
	   ('Ming_Dynasty_ALPHA_ATLAS', 48, 'ALPHA_ICON_Ming_Dynasty48.dds',  1, 1),
	   ('Ming_Dynasty_ALPHA_ATLAS', 32, 'ALPHA_ICON_Ming_Dynasty32.dds',  1, 1),
	   ('Ming_Dynasty_ALPHA_ATLAS', 24, 'ALPHA_ICON_Ming_Dynasty24.dds',  1, 1),
	   ('Ming_Dynasty_ALPHA_ATLAS', 16, 'ALPHA_ICON_Ming_Dynasty16.dds',  1, 1),
	   ('Ming_Dynasty_FLAG_ATLAS', 32,'FLAG_Ming_Dynasty.dds',4, 4); 